      SUBROUTINE D0SINT ( WORK, INDX, IER )
C
C ... STORES AN INTEGER VALUE IN A NON-INTEGER VARIABLE
C
C ... THE WORK ARRAY CONTAINS BOTH REAL AND INTEGER VALUES.
C     SOMETIMES AN INTEGER VALUE NEEDS TO BE STORED IN WORK,
C     BUT THE WORK ARRAY IS DECLARED REAL, D.P., ETC. IN THAT
C     PARTICULAR SUBROUTINE. D0SINT IS THEN USED.
C
C ... WRITTEN BY KAREN J. EKBLAD NOVEMBER 1985
C
      INTEGER WORK(*), INDX, IER
C
      WORK(INDX) = IER
C
      RETURN
C
      END
