      INTEGER FUNCTION DTDCLB(X)

      DOUBLE PRECISION  X

C CODE GENERATED FROM MASTER SOURCE FILE JH7CLB
C DATE OF LAST REVISION: 25 JULY 1986
C
C RESULT = 1  IF X IS THE CLOBBER CONSTANT
C        = 0  OTHERWISE
C
C MIXED MODE EQUIVALENCE IS USED
C
C PROGRAMMED BY STUART L. ANDERSON - 14 OCTOBER 1985

      INTEGER  ISU,JCLOBR,NDIM

      PARAMETER ( ISU = 15 , JCLOBR = 1 , NDIM = 4 )

      INTEGER  ICLOB(NDIM),IVALU(NDIM),DTJCON, I

      DOUBLE PRECISION  DTMCON, ACLOB, AVALU

      INTRINSIC  MIN
      EXTERNAL   DTMCON, DTJCON

      EQUIVALENCE  (ICLOB,ACLOB), (IVALU,AVALU)

C-------------------

      ACLOB  = DTMCON(JCLOBR)
      AVALU  = X
      DTDCLB = 0
      DO 10 I = 1, MIN(NDIM,DTJCON(ISU))
         IF ( ICLOB(I) .NE. IVALU(I) ) RETURN
   10 CONTINUE
      DTDCLB = 1

      END
