      SUBROUTINE DTERPT(ITYP)
C
C     THIS SUBROUTINE CAUSES THE SUBROUTINE TO EITHER TURN OFF ALL ERROR
C     COUNTING AND MESSAGE PRINTING, OR THIS SUBROUTINE MAY CAUSE THE
C     SUBROUTINE DTERR TO RESUME THE STATUS OF ERROR COUNTING AND
C     MESSAGE PRINTING THAT EXISTED PRIOR TO THE LAST CALL TO THIS
C     SUBROUTINE.
C
C   MODIFIED FOR FTN5 BY V. SINGSAAS/G. EDGAR 11/85.
C
C     USAGE -
C              CALL DTERPT(ITYP)
C
C     WHERE ITYPE IS A VARIABLE OF TYPE INTEGER
C
C      IF ITYP.EQ.0  THEN TURN OFF ALL ERROR COUNTING AND MESSAGE
C                        PRINTING CAPABILITIES OF DTERR.
C
C      IF ITYP.EQ.1  THEN
C                     IF ERROR COUNTING IS TURNED OFF THEN
C                          REVERT TO STATUS PRIOR TO LAST DTERPT CALL.
C                     IF ERROR COUNTING IS TURNED ON THEN
C                          DO NOTHING.
C
C      OTHERWISE - DO NOTHING
C
      CHARACTER*8 A
      INTEGER B,C, MODE
      IF(ITYP.EQ.  1 ) THEN
       MODE = -6
       ENDIF
      IF(ITYP.EQ.0) THEN
       MODE = -5
       ENDIF
      IF( (ITYP.GE.0) .AND. (ITYP.LE.1) ) CALL DTERR(MODE,A,B,C)
      RETURN
      END
