      SUBROUTINE DTERRS(ITYP,IVAL)
C
C**** DEFAULT CHANGE ROUTINE FOR THE STANDARD ERROR HANDLER (DTERR)
C
C     MODIFIED FOR FTN5 BY V. SINGSAAS/G. EDGAR   11/85.
C
C INPUT VARIABLES
C
C     ITYP - THE TYPE OF DEFAULT TO BE CHANGED.
C
C     IVAL - THE REPLACEMENT VALUE (IGNORED IF ITYP.EQ.2)
C
C USAGE OF DTERRS
C
C     CALL DTERRS(ITYP,IVAL)
C
C
C     IF ITYP.EQ.1
C         SET THE DTERR PRINT UNIT TO IVAL IF IVAL.NE.0
C         SUPPRESS ERROR MESSAGES IF IVAL.EQ.0
C
C     IF ITYP.EQ.2
C         RESTORE THE DEFAULT VALUE OF THE DTERR PRINT UNIT.
C
C     IF ITYP.EQ.3
C         SET THE MAXIMUM NUMBER OF FUTURE ERROR AND WARNING
C         MESSAGES TO MAX(IVAL,0).
C
C     IF NONE OF THE ABOVE HOLD, DO NOTHING.
C
C
C SUBROUTINE CALLED - DTERR
C
C PROGRAMMED BY STUART L. ANDERSON - 10 DEC. 1979
C
C     MODIFIED FOR FTN5 BY V. SINGSAAS/G. EDGAR  11/85.
C
      CHARACTER*8 DUMMY
C
C * * * * * * * * * * * * * * * * * * * * * * * * * * * START OF CODE
C
C**** TEST INPUT AND CALL DTERR TO PERFORM ACTION
C
      N = IVAL
      IF(ITYP.NE.1)GO TO 10
          MODE = -2
          IF(N.NE.0)GO TO 30
          MODE = -3
          N    = -1
          GO TO 30
C
   10 IF(ITYP.NE.2)GO TO 20
          MODE = -4
          GO TO 30
C
   20 IF(ITYP.NE.3)RETURN
          IF(N.LE.0)N = -1
          MODE = -3
C
   30 CALL DTERR(MODE,DUMMY,0,N)
      RETURN
      END
