      DOUBLE PRECISION FUNCTION DTFCTL (N)
C
C     COMPUTE THE FACTORIAL OF N
C
      DOUBLE PRECISION PROD
      INTEGER N, I
C
      PROD = 1.0
      DO 100 I = 1, N
          PROD = PROD * I
  100 CONTINUE
      DTFCTL = PROD
      RETURN
      END
