C**********************************************************************
      SUBROUTINE DTLCST(ADATA1,ADATA2,MAXDAT,NDIM,ALPHA,BETA,GAMMA,
     $                  ADATAC,IER)
C***********************************************************************
C
C FUNCTION-
C           LINEAR COMBINATION OF TWO STRINGS
C
C AUTHORS-
C          C.P.CHI             CREATION  OCTOBER   1989
C
C INPUT-
C          ADATA1 = ARRAY CONTAINING DATA FOR THE FIRST DATA SET
C          ADATA2 = ARRAY CONTAINING DATA FOR THE SECOND DATA SET
C          MAXDAT = MAX NUMBER OF DATA
C          NDIM   = DIMENSION OF THE DATA ARRAY
C          ALPHA  = CONSTANT FOR MODIFY THE FIRST DATA SET
C          BETA   = CONSTANT FOR MODIFY THE SECOND DATA SET
C          GAMMA  = ADDITIONAL CONSTANT FOR THE OUTPUT DATA SET
C
C OUTPUT-
C          SDATAC = ARRAY CONTAINING DATA FOR THE COMBINED DATA SET
C          IER    = ERROR FLAG
C                 = 0   NO ERROR
C                 =-65  INVALID DIMENSIONS FOR THE DATA ARRAYS
C
C
C REFERENCES-
C          1.
C
C NOTES-
C
C TYPE/PARAMETER/DIMENSION/COMMON/EQUIVALENCE/DATA/FORMAT STATEMENTS-
C
      DOUBLE PRECISION ADATA1(MAXDAT,NDIM), ADATA2(MAXDAT,NDIM),
     $                 ADATAC(MAXDAT,NDIM)
      DOUBLE PRECISION ALPHA, BETA, GAMMA
C
C ********************** START OF EXECUTABLE CODE **********************
C
      IER=0
C
C...CHECK INPUT DATA ARRAYS
C
      IF(MAXDAT.LE.0.OR.NDIM.LE.0) THEN
        IER=-65
        GOTO 999
      ENDIF
C
C...LINEAR COMBINATION OF THE DATA ARRAY
C
      DO 200 J=1, NDIM
      DO 100 I=1, MAXDAT
      ADATAC(I,J)=ALPHA*ADATA1(I,J)+BETA*ADATA2(I,J)+GAMMA
  100 CONTINUE
  200 CONTINUE
C
  999 CONTINUE
      RETURN
      END
