C**********************************************************************
      SUBROUTINE DTLCMS(SDATA1,SDATA2,TDATA1,TDATA2,MAXDAT,NDIM,
     $                  ALPHA,BETA,GAMMA,SDATAC,TDATAC,IER)
C***********************************************************************
C
C FUNCTION-
C           LINEAR COMBINATION OF TWO MESHES
C
C AUTHORS-
C          C.P.CHI             CREATION  OCTOBER   1989
C
C INPUT-
C          SDATA1 = ARRAY CONTAINING DATA FOR THE FIRST DATA SET IN
C                   THE DIRECTION OF THE FIRST INDEPENDENT VARIABLE
C          SDATA2 = ARRAY CONTAINING DATA FOR THE SECOND DATA SET IN
C                   THE DIRECTION OF THE FIRST INDEPENDENT VARIABLE
C          TDATA1 = ARRAY CONTAINING DATA FOR THE FIRST DATA SET IN
C                   THE DIRECTION OF THE SECOND INDEPENDENT VARIABLE
C          TDATA2 = ARRAY CONTAINING DATA FOR THE SECOND DATA SET IN
C                   THE DIRECTION OF THE SECOND INDEPENDENT VARIABLE
C          MAXDAT = MAX NUMBER OF DATA
C          NDIM   = DIMENSION OF THE DATA ARRAY
C          ALPHA  = CONSTANT FOR MODIFY THE FIRST DATA SET
C          BETA   = CONSTANT FOR MODIFY THE SECOND DATA SET
C          GAMMA  = ADDITIONAL CONSTANT FOR THE OUTPUT DATA SET
C
C OUTPUT-
C          SDATAC = ARRAY CONTAINING DATA FOR THE COMBINED DATA SET
C                   FOR THE FIRST INDEPENDENT VARIABLE
C          TDATAC = ARRAY CONTAINING DATA FOR THE COMBINED DATA SET
C                   FOR THE SECOND INDEPENDENT VARIABLE
C          IER    = ERROR FLAG
C                 = 0   NO ERROR
C                 =-65  INVALID DIMENSIONS FOR THE DATA ARRAYS
C
C REFERENCES-
C          1.
C
C NOTES-
C
C TYPE/PARAMETER/DIMENSION/COMMON/EQUIVALENCE/DATA/FORMAT STATEMENTS-
C
      DOUBLE PRECISION SDATA1(MAXDAT,NDIM), SDATA2(MAXDAT,NDIM),
     $                 SDATAC(MAXDAT,NDIM)
      DOUBLE PRECISION TDATA1(MAXDAT,NDIM), TDATA2(MAXDAT,NDIM),
     $                 TDATAC(MAXDAT,NDIM)
      DOUBLE PRECISION ALPHA, BETA, GAMMA
C
C ********************** START OF EXECUTABLE CODE **********************
C
      IER=0
C
C...CHECK INPUT DATA ARRAYS
C
      IF(MAXDAT.LE.0.OR.NDIM.LE.0) THEN
        IER=-65
        GOTO 999
      ENDIF
C
C...LINEAR COMBINATION OF THE DATA ARRAY
C
      DO 200 J=1, NDIM
      DO 100 I=1, MAXDAT
      SDATAC(I,J)=ALPHA*SDATA1(I,J)+BETA*SDATA2(I,J)+GAMMA
  100 CONTINUE
  200 CONTINUE
C
      DO 400 J=1, NDIM
      DO 300 I=1, MAXDAT
      TDATAC(I,J)=ALPHA*TDATA1(I,J)+BETA*TDATA2(I,J)+GAMMA
  300 CONTINUE
  400 CONTINUE
C
  999 CONTINUE
      RETURN
      END
