C     CALLED ONLY FROM DTRDIG
      SUBROUTINE DTRDI1 (IGES, ROW, COL, VALUE)

      DOUBLE PRECISION VALUE
      CHARACTER*16 IGES(5,*)
      INTEGER ROW, COL

      READ (IGES(COL,ROW)(1:15),10) VALUE
10    FORMAT (E15.8)
      COL = COL + 1
      IF (COL.LE.4) RETURN
      ROW = ROW + 1
      COL = 1
      END
