      DOUBLE PRECISION FUNCTION DTSFA1 (U, V, C, WORK, DNWORK)
C
C
C   INTEGRAND FUNCTION FOR DTSFAR'S CALL TO DTDIGL.
C     COMPUTES LENGTH OF SURFACE NORMAL AT PARAMETER VALUES (U,V).
C     THIS IS THE ABSOLUTE VALUE OF THE CROSS PRODUCT OF THE TWO
C     FIRST PARTIAL DERIVATIVES.
C
C   CALLS:
C     DTSRFN
C*****
      DOUBLE PRECISION U, V, C(*), WORK(*), DNWORK
C
      INTEGER NWORK
      DOUBLE PRECISION X(2), VNORM(3), CROSS
      INTEGER IER
C
      NWORK = INT (DNWORK)
      X(1) = U
      X(2) = V
C     BYPRODUCT OF COMPUTING SURFACE NORMAL IS SQUARE OF ITS LENGTH.
      CALL DTSRFN (X, 1, C, WORK, NWORK, VNORM, CROSS, IER)
      IF (IER .NE. 0) CROSS = 0.0D0
      DTSFA1 = SQRT (CROSS)
      RETURN
      END
