      SUBROUTINE DTWRI1 (VALUE, IGES, ROW, COL)
 
C----- THE FOLLOWING ROUTINE LOADS INFORMATION INTO THE IGES FILE
 
      DOUBLE PRECISION VALUE
      CHARACTER*16 IGES(5,*)
      INTEGER ROW, COL
 
      WRITE (IGES(COL,ROW),10) VALUE
10    FORMAT (E15.8,',')
      COL = COL + 1
      IF (COL.LE.4) RETURN
      WRITE (IGES(5,ROW),20) ROW - 6
20    FORMAT (' 0000001P',I7)
      ROW = ROW + 1
      COL = 1
      END
